### ISSUE TITLE
AD7200

### ISSUE THREAD

**Issue by ReenigneArcher** [menahishayan/TP-Link-Archer-C50-API#3]
Anyway this will work for an AD7200 router? I am only looking for a method to restart the router using an automation.

My python script is as follows.

```
import tplinkrouter
router = tplinkrouter.C50('192.168.1.1','myemail@gmail.com','myPassword')
```

which returns the following:
`Metadata Update Error.`

**Comment by menahishayan** [comment]
[\_\_init\_\_.py: Line 41 to Line 47](https://github.com/menahishayan/TP-Link-Archer-C50-API/blob/0532e5678c4f38dab118f36d6f3f1c6a91e1c36b/tplinkrouter/__init__.py#L41)
````python
        try:
            about = self._get('about')['[0,0,0,0,0,0]0']
            self.__name__ = about['modelName']
            self.description = about['description']
            self.__version__ = self._get('version')['[0,0,0,0,0,0]0']['softwareVersion'].split()[4]
        except:
            self.log("Metadata Update Error.")
````
remove the `try` and `except` blocks and add print/log statements to attempt to debug the issue

Your code would be something like:
````python
            about = self._get('about')['[0,0,0,0,0,0]0']
            print(about)
            self.__name__ = about['modelName']
            self.description = about['description']
            self.__version__ = self._get('version')['[0,0,0,0,0,0]0']['softwareVersion'].split()[4]
````

**Note:** If you've installed this via pip then your changes will not reflect due to python's cache. Download the script from this repo and import the local file manually

-----------
### Edit

It's highly unlikely that this script will work AS-IS for the AD7200. Instead of a failed attempt at modifying the code as mentioned above, I'd suggest following the instructions mentioned in [CONTRIBUTING.md](https://github.com/menahishayan/TP-Link-Archer-C50-API/blob/master/CONTRIBUTING.md) to add support for your model

**Comment by ReenigneArcher** [comment]
I ended up writing my own script to reboot the router: https://github.com/ReenigneArcher/JBOHAS/blob/main/scripts/python/tp_link_reboot.py

It runs inside of home assistant using selenium web driver.

**Comment by itsboo07** [comment]
hey how did you Manage to run the script inside home assistant ?

> I ended up writing my own script to reboot the router: https://github.com/ReenigneArcher/JBOHAS/blob/main/scripts/python/tp_link_reboot.py
> 
> It runs inside of home assistant using selenium web driver.

**Comment by ReenigneArcher** [comment]
> hey how did you Manage to run the script inside home assistant ?

Been quite a while since I added this, so not 100% sure. I think I used this as reference: https://community.home-assistant.io/t/using-selenium-with-chromedriver/259864/5

I think I used a command line sensor, but not 100% sure.
